// Questions d'entretien : ce que le jury évalue, comment structurer, pièges à éviter.
// Rappel (source officielle) : deux entretiens, l'un avec un jury de 2 personnels navigants,
// l'autre avec un officier psychologue du CERP'Air.

export const THEMES = ['Présentation et parcours', 'Motivation pour le pilotage', 'Engagement militaire', 'Valeurs et personnalité', 'Culture et actualité', 'Questions déstabilisantes'];

const Q = (theme, q, attendu, plan, pieges) => ({ theme, q, attendu, plan, pieges });
const [P, MO, MI, V, C, D] = THEMES;

export const QUESTIONS = [
  Q(P, 'Présentez-vous.', 'Ta capacité à te présenter clairement en 2 à 3 minutes, et le lien entre ton parcours et ton projet.', 'Plan « passé → présent → futur » : d’où tu viens (scolarité, bac spé maths/SES, BIA), ce que tu fais aujourd’hui (L1 de droit, sport, préparation), ce que tu veux faire (EOPN, pilote) et pourquoi.', 'Réciter ton CV mot pour mot ; parler 30 secondes ou 8 minutes ; oublier de parler de ton projet.'),
  Q(P, 'Pourquoi avoir commencé une licence de droit si vous voulez être pilote ?', 'La cohérence de ton parcours et ton honnêteté. Un parcours non linéaire n’est pas un problème s’il est assumé.', 'Explique le choix initial (intérêt réel, prudence, attente de l’âge/de la sélection), ce que le droit t’apporte (rigueur, expression écrite et orale, compréhension des institutions, droit des conflits armés) et comment ton projet s’est confirmé.', 'Dénigrer le droit (« c’était en attendant ») ; donner l’impression de fuir quelque chose.'),
  Q(P, 'Parlez-moi de votre scolarité et de vos résultats.', 'Ta lucidité sur tes points forts et faibles, et ta capacité à progresser.', 'Présente les faits sans te cacher, puis montre ce que tu as fait pour progresser (plan de travail en maths, entraînement régulier, résultats obtenus depuis).', 'Mentir ou minimiser ; accuser les professeurs.'),
  Q(P, 'Quelles sont vos trois principales qualités ?', 'Ta connaissance de toi-même et des exemples concrets.', 'Choisis 3 qualités utiles au métier (rigueur, sang-froid, esprit d’équipe, persévérance…) et donne pour chacune un exemple vécu court.', 'Une liste d’adjectifs sans preuve ; des qualités sans lien avec le métier.'),
  Q(P, 'Quel est votre principal défaut ?', 'Ta sincérité et ta capacité à travailler sur toi.', 'Un vrai défaut (pas « je suis trop perfectionniste »), non rédhibitoire pour un pilote, puis ce que tu fais concrètement pour le corriger.', 'Un faux défaut ; un défaut grave pour la sécurité (« je panique », « je ne supporte pas l’autorité »).'),
  Q(P, 'Racontez-moi un échec et ce que vous en avez retiré.', 'Ta résilience et ta capacité d’analyse (très proche du débriefing en aviation).', 'Méthode STAR : Situation, Tâche, Action, Résultat — puis la leçon tirée et ce que tu fais différemment aujourd’hui.', 'Dire que tu n’as jamais échoué ; rejeter la faute sur les autres.'),
  Q(P, 'Que faites-vous en dehors des cours ?', 'Ton équilibre, ton engagement, ton goût de l’effort et du collectif.', 'Sport (et ta préparation physique), activités associatives ou de groupe, aéronautique (BIA, aéroclub, lectures). Montre ce que chaque activité t’apporte.', 'Ne citer que des activités passives ; inventer une passion que tu ne peux pas détailler.'),
  Q(P, 'Pourquoi avez-vous passé le BIA ? Qu’en avez-vous retenu ?', 'L’ancienneté et la profondeur de ton intérêt pour l’aéronautique.', 'Raconte d’où vient l’envie, ce que tu as appris (aérodynamique, météo, navigation…), un sujet qui t’a passionné, et ce que tu as fait ensuite.', 'Ne plus rien savoir du programme : révise le module Culture & BIA !'),

  Q(MO, 'Pourquoi voulez-vous devenir pilote ?', 'Une motivation réfléchie, personnelle, qui va au-delà du « rêve d’enfant ».', 'Origine de l’envie (un déclic, une rencontre, un vol), ce qui t’attire dans le métier (responsabilité, exigence, travail en équipage, mission), ce que tu as fait pour vérifier ton choix (BIA, rencontres, journées portes ouvertes, lectures).', 'Ne parler que de sensations (« la vitesse, l’adrénaline ») ; citer seulement des films.'),
  Q(MO, 'Pourquoi pilote militaire et pas pilote de ligne ?', 'Que tu as compris la différence : la mission et l’engagement au service du pays.', 'Le sens du service et de la mission (protéger, intervenir, secourir), la diversité des missions, la dimension collective et militaire. Tu peux respecter le métier de pilote de ligne tout en expliquant pourquoi ce n’est pas ton projet.', 'Laisser entendre que l’armée est une formation gratuite avant de partir dans le civil.'),
  Q(MO, 'Chasse, transport, hélicoptère : avez-vous une préférence ?', 'Que tu connais les spécialités et que tu restes ouvert : c’est l’armée qui oriente selon les besoins et tes résultats.', 'Tu peux exprimer une préférence argumentée, puis montrer que les autres spécialités t’intéressent aussi (missions, équipage…). Connais les avions de chaque filière.', 'Dire « chasse ou rien ».'),
  Q(MO, 'Si vous êtes orienté navigateur officier systèmes d’armes (NOSA) ou pilote de drone, que ferez-vous ?', 'Ton adhésion au projet militaire au-delà du seul pilotage.', 'Montre que tu connais ces métiers (le NOSA gère navigation, capteurs et armement ; le pilote de drone mène des missions longues de renseignement et de frappe) et que tu les accepterais avec motivation.', 'Avoir l’air déçu ou dire que tu refuserais.'),
  Q(MO, 'Connaissez-vous le déroulement de la formation ?', 'Que tu t’es renseigné sérieusement.', 'Formation militaire initiale à l’École de l’air et de l’espace (Salon-de-Provence), puis formation en vol selon la filière (ex. : Cognac sur PC-21 pour la chasse), jusqu’au brevet. Vérifie les détails à jour auprès de ton CIRFA et sur devenir-aviateur.gouv.fr.', 'Inventer des durées ou des étapes : dis-le si tu n’es pas sûr.'),
  Q(MO, 'Avez-vous déjà volé ?', 'Ton contact réel avec l’aviation.', 'Raconte une expérience (baptême, vol d’initiation, simulateur, planeur) et ce que tu as ressenti / appris. Si tu n’as jamais volé, dis-le simplement et explique ce que tu as fait d’autre.', 'Exagérer ton expérience : le jury est composé de pilotes.'),
  Q(MO, 'Que ferez-vous si vous n’êtes pas retenu ?', 'Ta maturité et ta persévérance (et que tu as un plan B réfléchi).', 'Analyser les résultats, retenter si c’est possible, continuer tes études ; éventuellement d’autres voies vers l’aviation militaire. Montre que l’échec ne t’arrêterait pas.', 'Dire que tu n’as pas de plan B, ou qu’un plan B te conviendrait tout autant.'),
  Q(MO, 'Qu’est-ce qui vous fait penser que vous avez les qualités d’un pilote ?', 'Le lien entre ce que tu es et les exigences du métier.', 'Cite 2-3 exigences (gestion du stress, rigueur, priorisation, travail en équipe, condition physique) et pour chacune une preuve tirée de ton expérience.', 'Te comparer aux autres candidats ; affirmer sans preuve.'),

  Q(MI, 'Pourquoi voulez-vous devenir militaire ?', 'Que l’engagement militaire est un choix, pas un passage obligé pour piloter.', 'Le sens du service, la défense du pays, les valeurs, la vie en collectif, la fierté de l’uniforme. Appuie-toi sur un exemple ou une rencontre.', 'Ne parler que de l’avion.'),
  Q(MI, 'Que représente pour vous un engagement initial de 10 ans ?', 'Ta compréhension de la durée et de l’engagement.', 'C’est l’investissement de l’armée dans ta formation et ta contrepartie ; tu y as réfléchi, tu en as parlé à tes proches, cela correspond à ton projet de vie.', 'Avoir l’air surpris ou parler de quitter rapidement l’armée.'),
  Q(MI, 'Êtes-vous prêt à partir en opération, loin de vos proches, parfois longtemps ?', 'Ta lucidité sur les contraintes du métier.', 'Oui, en montrant que tu connais la réalité (opérations extérieures, alertes, mutations) et que ton entourage est au courant et te soutient.', 'Répondre « oui » sans réflexion ; minimiser les contraintes.'),
  Q(MI, 'Seriez-vous capable d’ouvrir le feu, en sachant que cela peut coûter des vies ?', 'Ta réflexion sur la finalité de l’arme et sur le cadre légal.', 'Réponse posée : l’usage de la force se fait sur ordre, dans un cadre légal (droit des conflits armés, règles d’engagement), pour protéger. Tu y as réfléchi sérieusement. Ta licence de droit peut nourrir la réponse.', 'Une réponse légère ou « va-t-en-guerre » ; refuser d’y réfléchir.'),
  Q(MI, 'Que pensez-vous de la discipline et de la hiérarchie ?', 'Ton rapport à l’autorité et au cadre.', 'La discipline garantit la sécurité et l’efficacité (en vol, chaque procédure compte). Obéir n’empêche pas de signaler un problème par les voies appropriées.', 'Avoir l’air d’accepter tout sans réflexion, ou au contraire de mal supporter les règles.'),
  Q(MI, 'Qu’en pense votre entourage ?', 'Le soutien dont tu disposes et ta maturité dans ta décision.', 'Explique que tu en as parlé, les éventuelles inquiétudes et comment tu y as répondu.', 'Dire que tu ne leur en as pas parlé.'),

  Q(V, 'Quelles sont pour vous les valeurs d’un militaire ?', 'Ta connaissance et ton adhésion aux valeurs.', 'Choisis 3-4 valeurs (sens du devoir, courage, loyauté, discipline, esprit d’équipe, intégrité, respect) et illustre-les par des exemples personnels ou historiques.', 'Une liste récitée sans exemple.'),
  Q(V, 'Donnez un exemple de travail en équipe réussi.', 'Ta place dans un groupe : écoute, coopération, prise d’initiative.', 'Méthode STAR, en insistant sur TON rôle et sur la manière dont le groupe a fonctionné.', 'Dire « je » partout ou « on » partout sans montrer ta contribution.'),
  Q(V, 'Racontez une situation stressante et comment vous l’avez gérée.', 'Ton sang-froid et tes méthodes (essentiel pour un pilote).', 'STAR + ta méthode (respirer, prioriser, se concentrer sur l’action suivante). En aviation : « aviate, navigate, communicate » (piloter d’abord, naviguer ensuite, communiquer enfin).', 'Choisir un exemple sans enjeu ; dire que tu ne stresses jamais.'),
  Q(V, 'Avez-vous déjà dirigé un groupe ?', 'Ton potentiel d’officier (tu encadreras des équipes).', 'Un exemple de responsabilité (capitaine d’équipe, projet, association, job) : comment tu as fixé un objectif, réparti le travail, géré un désaccord.', 'Confondre diriger et imposer.'),
  Q(V, 'Comment réagissez-vous face à une critique ?', 'Ta capacité à progresser, clé du débriefing en aviation.', 'Écouter jusqu’au bout, demander des précisions, remercier, corriger. Donne un exemple où une critique t’a fait progresser.', 'Dire que tu n’es jamais critiqué.'),
  Q(V, 'Que feriez-vous en cas de désaccord avec un supérieur ?', 'Loyauté et capacité à s’exprimer de façon constructive.', 'Exécuter l’ordre s’il est légal, exprimer son point de vue au bon moment et de façon argumentée (en vol : dire clairement un doute de sécurité, c’est la logique du CRM).', 'Désobéir ; ou ne jamais rien dire même face à un danger.'),

  Q(C, 'Quelles sont les missions de l’Armée de l’Air et de l’Espace ?', 'Ta connaissance de l’institution que tu veux rejoindre.', 'Protection de l’espace aérien (posture permanente de sûreté aérienne), dissuasion nucléaire (FAS), intervention et projection (opérations extérieures), renseignement, transport et ravitaillement, missions spatiales (Commandement de l’espace), sauvetage.', 'Ne citer que « faire la guerre ».'),
  Q(C, 'Quels avions de l’Armée de l’Air et de l’Espace connaissez-vous ?', 'Ton intérêt réel pour le matériel.', 'Rafale (omnirôle), Mirage 2000, A400M Atlas, A330 MRTT Phénix, E-3F AWACS, PC-21, Alphajet (Patrouille de France), Caracal, Reaper… Sois capable de dire un mot sur chacun.', 'Confondre avec des avions étrangers ou de la Marine.'),
  Q(C, 'Parlez-moi d’une actualité de défense récente.', 'Que tu suis l’actualité et que tu sais la commenter avec mesure.', 'Choisis 1 ou 2 sujets récents (guerre en Ukraine, loi de programmation militaire, coopérations européennes, espace…). Résume les faits, puis donne une analyse mesurée.', 'Ne rien avoir lu ; donner un avis politique tranché.'),
  Q(C, 'Qui est le chef des armées ? Qui est votre ministre ?', 'Ta connaissance des institutions (et c’est ta matière en droit !).', 'Le Président de la République est le chef des armées (art. 15 de la Constitution). Vérifie avant l’entretien les noms actuels du ministre des Armées, du CEMA et du CEMAAE.', 'Hésiter sur l’article 15 alors que tu es en droit.'),
  Q(C, 'À quoi sert la dissuasion nucléaire ?', 'Ta compréhension d’un enjeu stratégique majeur porté par l’AAE.', 'Garantir la protection des intérêts vitaux de la France en dissuadant toute agression ; deux composantes, océanique et aéroportée (FAS) ; décision du Président.', 'Confondre dissuasion et emploi offensif.'),

  Q(D, 'Pourquoi vous plutôt qu’un autre candidat ?', 'Ta capacité à te valoriser sans arrogance.', 'Résume ce qui fait ta valeur : motivation ancienne et vérifiée, travail fourni (préparation méthodique), qualités prouvées par des exemples.', 'Dénigrer les autres ; répondre « je ne sais pas ».'),
  Q(D, 'Vous aviez 7/20 en maths au bac. Comment pouvez-vous réussir ?', 'Ta lucidité et ta capacité de travail face à une faiblesse.', 'Reconnais le fait, explique-le sans excuse, puis montre le plan mis en place et les progrès mesurés (régularité, chapitres refaits depuis la seconde, résultats aux tests d’entraînement).', 'Minimiser (« les maths ne servent pas à un pilote ») ; se justifier longuement.'),
  Q(D, 'Qu’est-ce qui pourrait vous faire abandonner ?', 'Ta solidité et ta réflexion.', 'Une réponse honnête et réfléchie (une raison grave, médicale ou familiale), en montrant que les difficultés ordinaires (fatigue, éloignement, échecs) ne t’arrêteraient pas.', 'Répondre « rien » trop vite ou citer des difficultés normales du métier.'),
  Q(D, 'Avez-vous des questions à nous poser ?', 'Ta curiosité et ta préparation.', 'Prépare 1 ou 2 questions sincères (sur le quotidien en escadron, les qualités qu’ils jugent essentielles, leur parcours…).', 'Demander le salaire ou les congés en premier ; dire « non, rien ».'),
];

export const METHODE = `
  <h3>Comment se passe l’entretien ?</h3>
  <p>Selon devenir-aviateur.gouv.fr, il y a <b>deux entretiens individuels</b> : l’un avec un jury de <b>deux personnels navigants</b> (pilotes ou navigateurs), l’autre avec un <b>officier psychologue</b> du CERP’Air. Le jury vérifie ta motivation, ta connaissance du métier et ton adaptation à la fonction d’officier.</p>
  <h3>Structurer ses réponses</h3>
  <ul>
    <li><b>Présentation</b> : passé → présent → futur, en 2 à 3 minutes.</li>
    <li><b>Exemples vécus</b> : méthode <b>STAR</b> — Situation, Tâche, Action (ce que <i>toi</i> tu as fait), Résultat, puis la leçon tirée.</li>
    <li><b>Questions d’opinion</b> : réponse claire en une phrase, puis 2 arguments, puis un exemple.</li>
    <li>Une bonne réponse dure en général <b>1 à 2 minutes</b>.</li>
  </ul>
  <h3>Attitude</h3>
  <ul>
    <li>Tenue sobre et correcte (la source officielle cite par exemple une chemise blanche et un jean).</li>
    <li>Regarde les membres du jury, parle posément, tiens-toi droit.</li>
    <li>Si tu ne sais pas : dis-le honnêtement plutôt que d’inventer. Les pilotes valorisent l’honnêteté (c’est une question de sécurité des vols).</li>
    <li>Sois cohérent : le psychologue peut recouper tes réponses avec les questionnaires de personnalité.</li>
  </ul>
  <h3>S’entraîner</h3>
  <ol>
    <li>Rédige des notes pour chaque question (mots-clés, pas un texte à réciter).</li>
    <li>Lance la <b>simulation</b> : réponds à voix haute, chronomètre en marche. Enregistre-toi avec ton téléphone si possible.</li>
    <li>Fais-toi interroger par quelqu’un (la source officielle le recommande).</li>
  </ol>`;

export const CRITERES = ['J’ai répondu à la question posée', 'Ma réponse était structurée (début, développement, conclusion)', 'J’ai donné au moins un exemple concret', 'J’ai parlé entre 1 et 2 minutes sans me perdre', 'J’ai fait le lien avec le métier de pilote / d’officier'];
