// Épreuve de groupe (confirmée officiellement : au moins 4 candidats). Sujets d'entraînement,
// méthode, grille d'observation et banque de situations « bon comportement ».
// ⚠️ Le format exact (durée, type de sujet, consignes) n'est pas publié : ce sont des sujets d'entraînement.
import { registerBank } from '../core/bank.js';

export const TYPES = {
  survie: { ico: '🏝️', label: 'Survie / classement', desc: 'Classer des objets ou des priorités et se mettre d’accord sur un classement commun.' },
  probleme: { ico: '🧩', label: 'Problème à résoudre', desc: 'Trouver une solution concrète avec des contraintes (temps, moyens, personnes).' },
  debat: { ico: '💬', label: 'Débat', desc: 'Discuter d’une question ouverte et aboutir à une position argumentée du groupe.' },
  orga: { ico: '🗂️', label: 'Organisation', desc: 'Planifier un événement ou une mission avec des moyens limités.' },
};

export const SUJETS = [
  { type: 'survie', t: 'Atterrissage forcé dans le désert', txt: 'Votre avion s’est posé en urgence dans le désert, à 100 km de la piste la plus proche, en plein été. Vous pouvez emporter 12 objets récupérés : lampe torche, 4 L d’eau, carte de la région, miroir de poche, parachute, couteau, boussole, pistolet de détresse (2 fusées), trousse de secours, manteaux, sel, livre sur les plantes comestibles.', consigne: 'Classez ces objets du plus utile au moins utile et décidez : rester près de l’avion ou partir à pied ?', pistes: 'Les secours cherchent l’avion : rester près de l’épave est en général préférable. Priorités : protection contre la chaleur, signalisation (miroir, fusées), eau. La boussole et la carte servent peu si l’on reste.' },
  { type: 'survie', t: 'Naufrage en mer', txt: 'Après un amerrissage, votre équipage de 5 personnes est sur un canot de survie. Objets disponibles : bâche, radio de détresse (balise), 10 L d’eau, rations, rames, corde, miroir, crème solaire, couteau, sextant sans tables, carte maritime, rhum.', consigne: 'Classez les objets par ordre d’importance et répartissez les rôles à bord.', pistes: 'La balise de détresse passe en premier (elle fait venir les secours). Ensuite eau, protection contre le soleil, moyens de signalisation. Le sextant sans tables et la carte sont peu utiles.' },
  { type: 'survie', t: 'Perdus en montagne l’hiver', txt: 'Votre groupe est bloqué en montagne par une tempête de neige, à 1 jour de marche d’un village. Objets : sac de couchage, réchaud et cartouche, briquet, couverture de survie, pelle à neige, téléphone (10 % de batterie, réseau faible), barres énergétiques, corde, carte, lampe frontale.', consigne: 'Décidez d’un plan d’action pour les prochaines 24 h et classez les objets.', pistes: 'Priorité au froid : abri (pelle à neige), chaleur, s’isoler du sol. Utiliser le téléphone avec méthode : un seul appel bref ou un SMS, puis économiser la batterie.' },
  { type: 'survie', t: 'Station lunaire', txt: 'Votre module s’est posé à 300 km de la base lunaire. Objets : réservoirs d’oxygène, eau, carte des étoiles, émetteur-récepteur solaire, vivres concentrés, trousse médicale, corde, boussole, allumettes, parachute, pistolet de signalisation.', consigne: 'Classez les objets pour rejoindre la base.', pistes: 'Oxygène et eau d’abord. Sur la Lune, la boussole et les allumettes sont inutiles (pas de champ magnétique utilisable, pas d’oxygène pour la combustion).' },
  { type: 'survie', t: 'Évacuation d’un bâtiment', txt: 'Un incendie se déclare dans un bâtiment de 3 étages où vous êtes 6. L’escalier principal est enfumé. Vous disposez d’un extincteur, de serviettes, d’eau, d’un téléphone, d’une échelle de secours au 1er étage, d’une lampe.', consigne: 'Décidez de l’ordre des actions et de qui fait quoi.', pistes: 'Alerter (18 ou 112), éviter la fumée (se baisser, serviettes mouillées), ne pas prendre l’ascenseur, regrouper et compter les personnes, attendre les secours si la sortie est impossible.' },
  { type: 'survie', t: 'Équipement pour une mission polaire', txt: 'Vous préparez une mission de 2 semaines en Arctique avec un poids limité. Choisissez 8 objets parmi 15 : tente, réchaud, carburant, GPS, balise, fusil, raquettes, lunettes de glacier, médicaments, jeu de cartes, appareil photo, panneaux solaires, livres, vêtements de rechange, vivres déshydratés.', consigne: 'Le groupe doit se mettre d’accord sur 8 objets, en justifiant chaque choix.', pistes: 'Ce qui fait vivre (abri, chaleur, eau, nourriture), ce qui sécurise (balise, médicaments, lunettes), ce qui fait avancer (raquettes, GPS). Le confort passe en dernier.' },
  { type: 'probleme', t: 'Un pont à reconstruire', txt: 'Un village isolé par une crue a besoin d’un pont provisoire en 48 h. Vous avez 10 volontaires, un camion, du bois, des cordes et un budget de 5 000 €. La route de contournement fait 80 km.', consigne: 'Proposez un plan réaliste, avec étapes, rôles et risques.', pistes: 'Sécurité d’abord (évaluer le courant, ne pas travailler seul), répartition des tâches, solution de secours (navette par la route de contournement en attendant).' },
  { type: 'probleme', t: 'Répartir 3 avions pour 5 missions', txt: 'Votre escadron dispose de 3 avions disponibles demain. Missions demandées : évacuation sanitaire urgente, transport de matériel pour un exercice, entraînement d’un jeune pilote, transport d’une délégation officielle, reconnaissance météo.', consigne: 'Classez les missions par priorité et proposez une répartition.', pistes: 'La sauvegarde de vies humaines passe en premier. Expliquer ses critères (urgence, importance, possibilité de reporter) vaut plus que la réponse elle-même.' },
  { type: 'probleme', t: 'Bus en panne avant une cérémonie', txt: 'Le bus qui emmène 40 jeunes à une cérémonie militaire tombe en panne à 30 km. La cérémonie commence dans 1 h 30. Vous avez 4 voitures de bénévoles, un téléphone et le numéro des organisateurs.', consigne: 'Trouvez une solution et organisez-la.', pistes: 'Prévenir tout de suite les organisateurs, compter les places disponibles, faire plusieurs rotations, désigner un responsable par voiture, prévoir un plan B (arriver en retard mais au complet).' },
  { type: 'probleme', t: 'Un équipier démotivé', txt: 'Dans votre équipe de projet, un membre ne fait plus sa part depuis 3 semaines. L’échéance est dans 10 jours et le reste de l’équipe commence à se plaindre.', consigne: 'Que fait le groupe ? Proposez une démarche.', pistes: 'Parler d’abord avec la personne en privé (comprendre la cause), redistribuer si nécessaire, fixer des objectifs clairs, alerter le responsable seulement si rien ne change.' },
  { type: 'probleme', t: 'Réduire les déchets d’une base aérienne', txt: 'Le commandant d’une base de 2 000 personnes veut réduire de moitié les déchets en un an, avec un petit budget.', consigne: 'Proposez 5 mesures concrètes classées par efficacité.', pistes: 'Mesurer avant d’agir, cibler les plus gros postes (restauration, emballages), impliquer les personnels, fixer des indicateurs.' },
  { type: 'probleme', t: 'Secourir un randonneur', txt: 'Un randonneur blessé à la cheville appelle à l’aide depuis une zone sans route, à 2 h de marche. Il fait nuit dans 3 h. Vous êtes 5 avec une trousse de secours, des lampes et un téléphone.', consigne: 'Décidez du plan d’action.', pistes: 'Appeler les secours (112) avec une position précise, ne pas se mettre en danger, envoyer une équipe de 2 ou 3 avec du matériel, garder le contact.' },
  { type: 'debat', t: 'Faut-il rétablir le service militaire obligatoire ?', txt: 'Le service militaire obligatoire a été suspendu en 1997. Certains souhaitent son retour, d’autres préfèrent le volontariat (SNU, réserve, service civique).', consigne: 'Le groupe doit formuler une position commune, nuancée et argumentée.', pistes: 'Arguments : cohésion nationale, coût, besoins réels des armées professionnelles, encadrement nécessaire. Le jury regarde surtout comment vous construisez l’accord.' },
  { type: 'debat', t: 'Les drones remplaceront-ils les pilotes ?', txt: 'Les drones et l’intelligence artificielle progressent vite dans l’aviation militaire.', consigne: 'Le groupe doit répondre à la question en 3 arguments partagés.', pistes: 'Complémentarité homme-machine, jugement humain et responsabilité, vulnérabilité des liaisons, coût, éthique. Évite les positions caricaturales.' },
  { type: 'debat', t: 'Les réseaux sociaux et les militaires', txt: 'Un militaire publie des photos de sa base et de son unité sur les réseaux sociaux.', consigne: 'Le groupe doit proposer des règles de bon usage.', pistes: 'Sécurité opérationnelle (localisation, identités, matériels), réputation de l’institution, droit à la vie privée, pédagogie plutôt qu’interdiction totale.' },
  { type: 'debat', t: 'Faut-il des quotas de femmes chez les pilotes ?', txt: 'Les femmes restent peu nombreuses chez les pilotes de chasse.', consigne: 'Le groupe débat et propose des mesures pour attirer plus de candidates.', pistes: 'Distinguer égalité des chances et quotas, parler d’information, de modèles, de conditions de vie. Respect des avis différents.' },
  { type: 'debat', t: 'L’espace, nouveau champ de bataille ?', txt: 'L’Armée de l’air est devenue Armée de l’Air et de l’Espace en 2020, avec un Commandement de l’espace.', consigne: 'Le groupe explique pourquoi l’espace est devenu stratégique et ce que la France doit faire.', pistes: 'Satellites de renseignement, de communication et de navigation, menaces (brouillage, satellites espions, débris), surveillance de l’espace, coopération européenne.' },
  { type: 'debat', t: 'Écologie et aviation militaire', txt: 'L’aviation est critiquée pour ses émissions de CO₂.', consigne: 'Le groupe propose une position : l’armée doit-elle réduire ses vols ?', pistes: 'Simulateurs, carburants durables, optimisation, mais nécessité opérationnelle et entraînement réel. Chercher un équilibre.' },
  { type: 'orga', t: 'Organiser une journée portes ouvertes', txt: 'Vous devez organiser la journée portes ouvertes d’une base aérienne dans 2 mois : 5 000 visiteurs attendus, 20 bénévoles.', consigne: 'Établissez le plan : étapes, équipes, sécurité, communication.', pistes: 'Rétroplanning, responsables par pôle (accueil, sécurité, animations, restauration, communication), plan en cas de pluie, secours sur place.' },
  { type: 'orga', t: 'Préparer un déplacement d’escadron', txt: 'Votre escadron de 80 personnes et 10 avions part 3 semaines en exercice à l’étranger dans 1 mois.', consigne: 'Listez et classez ce qu’il faut organiser.', pistes: 'Transport des personnes et du matériel, pièces de rechange, hébergement, autorisations, santé (vaccins), communication avec les familles.' },
  { type: 'orga', t: 'Accueillir une promotion de nouveaux élèves', txt: 'Vous êtes chargés d’accueillir 60 nouveaux élèves la première semaine.', consigne: 'Proposez un programme de 5 jours.', pistes: 'Accueil administratif, découverte des lieux, cohésion (parrainage, activités sportives), règles de vie, présentation des traditions.' },
  { type: 'orga', t: 'Collecte pour une association', txt: 'Votre groupe veut récolter 3 000 € en 3 mois pour une association d’aide aux blessés de guerre.', consigne: 'Construisez le plan d’action.', pistes: 'Objectifs intermédiaires, plusieurs actions (course solidaire, vente, réseaux), répartition des rôles, suivi des résultats.' },
  { type: 'orga', t: 'Plan de révision commun', txt: 'Vous êtes 5 candidats qui passez la sélection dans 6 mois, avec des points forts différents (maths, anglais, sport, culture).', consigne: 'Organisez une préparation commune efficace.', pistes: 'Faire un état des lieux, entraide (chacun enseigne son point fort), calendrier réaliste, examens blancs réguliers, motivation du groupe.' },
  { type: 'orga', t: 'Panne de courant générale sur la base', txt: 'Une panne électrique touche toute la base pendant 12 h, en hiver.', consigne: 'Le groupe établit les priorités et l’organisation.', pistes: 'Activités vitales et opérationnelles d’abord (groupes électrogènes, alerte), sécurité des personnes, information, rationnement du carburant.' },
];

export const ROLES = [
  { ico: '🚀', r: 'Lanceur', d: 'Reformule le sujet au début et propose une méthode (« on liste, puis on classe, puis on vote ? »). Très bien vu s’il ne monopolise pas.' },
  { ico: '⏱️', r: 'Gardien du temps', d: 'Rappelle le temps restant. Utile, mais ce rôle seul ne suffit pas : il faut aussi apporter des idées.' },
  { ico: '🧠', r: 'Contributeur', d: 'Apporte des idées concrètes et argumentées. C’est la base : chaque candidat doit contribuer sur le fond.' },
  { ico: '🤝', r: 'Facilitateur', d: 'Donne la parole aux plus discrets (« Et toi, tu en penses quoi ? »), apaise les tensions. Très valorisé.' },
  { ico: '📝', r: 'Synthétiseur', d: 'Fait des points d’étape (« Si je résume, on est d’accord sur… ») et prépare la conclusion.' },
];

export const CRITERES_GROUPE = [
  'A pris la parole tôt, avec une intervention utile',
  'A apporté des idées concrètes et argumentées',
  'A écouté (reformule, rebondit sur les autres)',
  'A laissé la parole et fait participer les autres',
  'Est resté calme et respectueux en cas de désaccord',
  'A aidé le groupe à avancer (méthode, temps, synthèse)',
  'A su changer d’avis face à un bon argument',
  'Posture : regard vers tous, voix claire, pas de gestes parasites',
];

export const METHODE_GROUPE = `
  <p>L’épreuve de groupe réunit <b>au moins 4 candidats</b> autour d’un sujet, sous le regard d’observateurs (format confirmé par la source officielle ; durée et type de sujet non publiés). Le jury n’évalue <b>pas la bonne réponse</b> mais <b>ton comportement dans le groupe</b> : ce que tu apportes, comment tu écoutes, comment tu fais avancer.</p>
  <h3>Ce qui est observé</h3>
  <ul><li><b>Participation</b> : parler, mais à bon escient (ni muet, ni monopolisateur).</li><li><b>Écoute</b> : reformuler, rebondir, citer les idées des autres.</li><li><b>Leadership positif</b> : proposer une méthode, faire des synthèses, gérer le temps, intégrer les discrets.</li><li><b>Maîtrise de soi</b> : calme, respect, argumenter sans s’énerver.</li><li><b>Adaptabilité</b> : accepter un meilleur argument, chercher le consensus.</li></ul>
  <h3>Déroulé conseillé</h3>
  <ol><li><b>Lecture</b> : note 3 ou 4 idées et une proposition de méthode.</li><li><b>Démarrage</b> (2 premières minutes) : prends la parole tôt, reformule le sujet, propose une méthode simple.</li><li><b>Discussion</b> : donne tes idées avec un argument chacune ; rebondis (« Je rejoins X, et j’ajouterais… »).</li><li><b>Points d’étape</b> : « Il nous reste 5 minutes, on est d’accord sur A et B, il reste C. »</li><li><b>Conclusion</b> : une solution commune, même imparfaite, vaut mieux que pas de conclusion.</li></ol>
  <h3>Phrases utiles</h3>
  <ul><li>« Je propose qu’on commence par lister, puis qu’on classe. Ça vous va ? »</li><li>« Si je reformule ce que tu dis… »</li><li>« On n’a pas encore entendu Léa : qu’en penses-tu ? »</li><li>« Je ne suis pas d’accord, parce que… mais je comprends ton point sur… »</li><li>« Tu m’as convaincu, je change mon classement. »</li><li>« Si je résume où on en est… »</li></ul>
  <h3>Pièges</h3>
  <ul><li>Couper la parole, parler plus fort que les autres.</li><li>Rester silencieux 5 minutes « pour réfléchir ».</li><li>Vouloir gagner le débat au lieu de faire avancer le groupe.</li><li>Jouer un rôle artificiel (« je vais être le leader ») : le jury le voit.</li><li>S’adresser seulement au jury ou à une seule personne.</li></ul>
  <p class="tip">Entraîne-toi avec 3 ou 4 proches : un sujet de la liste, 20 minutes, et une personne en plus qui observe avec la grille. Puis échangez les rôles.</p>`;

const ITEMS = [
  { q: 'Le sujet vient d’être distribué. Personne ne parle depuis 20 secondes. Que fais-tu ?', a: 'Je reformule le sujet et propose une méthode au groupe', d: ['J’attends qu’un autre commence pour ne pas paraître autoritaire', 'Je donne directement la réponse que je pense juste', 'Je demande au jury ce qu’il attend'], e: 'Démarrer en proposant une <b>méthode</b> (et en demandant l’accord du groupe) est le meilleur départ : c’est utile et ce n’est pas autoritaire.' },
  { q: 'Un candidat parle sans arrêt et coupe les autres. Que fais-tu ?', a: 'Je reconnais son idée puis je donne la parole à quelqu’un qui ne s’est pas exprimé', d: ['Je lui dis qu’il est insupportable', 'Je parle plus fort que lui', 'Je ne dis plus rien jusqu’à la fin'], e: 'On gère la situation pour le groupe, sans agressivité : « Ton idée est intéressante. On n’a pas encore entendu Paul… »' },
  { q: 'Une candidate n’a encore rien dit après 10 minutes. Que fais-tu ?', a: 'Je l’invite à donner son avis', d: ['Je l’ignore : c’est son problème', 'Je fais remarquer au jury qu’elle ne participe pas', 'Je parle à sa place'], e: 'Faire participer les plus discrets montre ton sens du collectif, une qualité essentielle d’un futur officier.' },
  { q: 'Un autre candidat propose une idée meilleure que la tienne. Que fais-tu ?', a: 'Je le dis et je me range à son idée en expliquant pourquoi', d: ['Je défends la mienne jusqu’au bout', 'Je fais semblant de ne pas avoir entendu', 'Je critique son idée pour garder l’avantage'], e: 'Savoir changer d’avis face à un bon argument est une preuve de maturité et d’intelligence collective.' },
  { q: 'Il reste 3 minutes et le groupe n’a pas de conclusion. Que fais-tu ?', a: 'Je propose une synthèse des points d’accord et un choix rapide sur le reste', d: ['Je laisse le temps se terminer', 'Je relance un nouveau sujet de discussion', 'Je reproche au groupe d’avoir perdu du temps'], e: 'Une conclusion commune, même imparfaite, vaut mieux qu’aucune. Faire la synthèse est très valorisé.' },
  { q: 'Deux candidats s’opposent vivement. Que fais-tu ?', a: 'Je reformule les deux positions et cherche ce qu’elles ont en commun', d: ['Je prends parti pour le plus fort', 'Je les laisse se disputer', 'Je change de sujet sans rien dire'], e: 'Reformuler et chercher un terrain d’entente (ou un critère pour trancher) fait avancer le groupe et calme le jeu.' },
  { q: 'Tu n’es pas d’accord avec la proposition du groupe. Comment le dire ?', a: '« Je vois l’intérêt de cette idée, mais je pense que… parce que… »', d: ['« C’est n’importe quoi »', 'Je ne dis rien pour éviter le conflit', '« Vous avez tort, c’est évident »'], e: 'Un désaccord exprimé avec respect et argumenté est positif. Se taire ou attaquer ne l’est pas.' },
  { q: 'Pendant l’épreuve, à qui t’adresses-tu ?', a: 'À l’ensemble du groupe, en regardant tout le monde', d: ['Au jury, pour qu’il m’entende bien', 'À la personne la plus influente', 'Au candidat avec qui je suis d’accord'], e: 'Le jury observe un groupe : on parle au groupe, pas aux observateurs.' },
  { q: 'Tu ne connais rien au thème du débat. Que fais-tu ?', a: 'Je participe avec du bon sens, des questions et en aidant à organiser', d: ['Je me tais toute l’épreuve', 'J’invente des chiffres pour paraître informé', 'J’annonce au jury que le sujet est mal choisi'], e: 'On peut beaucoup apporter sans être expert : questions pertinentes, méthode, synthèses. Ne jamais inventer.' },
  { q: 'Quel est le principal objectif de l’épreuve de groupe pour le jury ?', a: 'Observer ton comportement et ta contribution au sein d’un groupe', d: ['Trouver la bonne réponse au sujet', 'Mesurer tes connaissances', 'Voir qui parle le plus'], e: 'Le sujet est un prétexte : ce sont les comportements (écoute, contribution, leadership, maîtrise de soi) qui sont évalués.' },
  { q: 'Tu as déjà beaucoup parlé. Un autre candidat veut intervenir en même temps que toi. Que fais-tu ?', a: 'Je lui laisse la parole', d: ['Je continue ma phrase', 'Je hausse le ton', 'Je lui dis d’attendre son tour'], e: 'Laisser la parole montre que tu sais partager l’espace. Tu pourras revenir ensuite.' },
  { q: 'Le groupe part dans une discussion hors sujet. Que fais-tu ?', a: 'Je ramène gentiment le groupe à la consigne', d: ['Je suis le mouvement', 'Je fais remarquer sèchement que c’est hors sujet', 'J’attends que le jury intervienne'], e: '« C’est intéressant, mais revenons à la consigne : il faut classer les objets. » Recadrer avec tact est un vrai leadership.' },
  { q: 'Comment montrer que tu écoutes vraiment ?', a: 'En reformulant et en reprenant les idées des autres avec leur nom', d: ['En hochant la tête en permanence', 'En prenant beaucoup de notes sans parler', 'En répétant ses propres idées'], e: '« Comme le disait Julie… » prouve une écoute réelle et valorise les autres.' },
  { q: 'Le groupe vote et ta proposition est rejetée. Comment réagir ?', a: 'J’accepte la décision et je contribue à la suite', d: ['Je boude', 'Je redemande un vote', 'Je dis au jury que le groupe s’est trompé'], e: 'Accepter une décision collective et s’y engager est une qualité attendue d’un militaire.' },
  { q: 'Faut-il chercher à être « le leader » à tout prix ?', a: 'Non : il faut être utile au groupe, le leadership vient naturellement', d: ['Oui, c’est ce que le jury veut voir', 'Oui, en parlant le premier et le plus', 'Non, il vaut mieux rester en retrait'], e: 'Le leadership recherché est un leadership de service : méthode, synthèse, inclusion. Un leader autoproclamé est mal perçu.' },
  { q: 'Tu sens le stress monter et ta voix trembler. Que faire ?', a: 'Respirer lentement, parler un peu plus lentement et poser une phrase courte', d: ['Ne plus parler', 'Parler très vite pour finir', 'Dire au groupe que tu es stressé et t’arrêter'], e: 'Une respiration lente et des phrases courtes aident à reprendre le contrôle. Le jury apprécie qu’on se reprenne.' },
  { q: 'Un candidat dit quelque chose de factuellement faux. Que fais-tu ?', a: 'Je corrige poliment avec mon information, sans le ridiculiser', d: ['Je me moque de lui', 'Je ne dis rien pour ne pas le gêner', 'Je le signale au jury'], e: 'Corriger avec tact (« Je crois que c’est plutôt… ») sert le groupe sans humilier personne.' },
  { q: 'Quelle est la meilleure façon de prendre la parole quand tout le monde parle ?', a: 'Attendre une courte pause et intervenir en rebondissant sur ce qui vient d’être dit', d: ['Couper la parole', 'Lever la main et attendre qu’on te la donne', 'Renoncer'], e: 'Rebondir (« Justement… ») permet d’entrer dans la discussion sans couper.' },
  { q: 'Le groupe a fini avant la fin du temps. Que faire ?', a: 'Vérifier la solution, ses risques et ce qu’on pourrait améliorer', d: ['Discuter d’autre chose', 'Rester silencieux', 'Annoncer au jury qu’on a fini'], e: 'Utiliser le temps restant pour consolider (risques, plan B) montre de la rigueur.' },
  { q: 'Un candidat attaque personnellement un autre. Que fais-tu ?', a: 'Je recadre calmement : on discute des idées, pas des personnes', d: ['Je rigole', 'Je soutiens celui qui attaque', 'Je quitte la discussion'], e: 'Recentrer sur les idées avec calme protège le groupe. Le jury observe ta maîtrise.' },
  { q: 'Dans une épreuve de classement, comment faire avancer un groupe bloqué ?', a: 'Proposer un critère commun pour décider (par exemple : ce qui sauve des vies d’abord)', d: ['Imposer son classement', 'Tirer au sort', 'Faire la moyenne sans discuter'], e: 'Se mettre d’accord sur les <b>critères</b> avant de classer débloque souvent la discussion.' },
  { q: 'Quelle posture adopter assis autour de la table ?', a: 'Droit, ouvert, mains visibles, regard vers les autres', d: ['Bras croisés pour paraître sûr de soi', 'Penché sur ses notes', 'Tourné vers le jury'], e: 'Une posture ouverte montre ton engagement dans le groupe.' },
  { q: 'Tu as proposé la méthode au début. Faut-il ensuite tout diriger ?', a: 'Non : je laisse le groupe s’approprier la discussion et j’interviens pour faire avancer', d: ['Oui, j’ai pris le rôle de chef', 'Oui, en distribuant la parole à chaque tour', 'Non, je ne dis plus rien'], e: 'Proposer une méthode ne donne pas un droit de contrôle. L’équilibre est la clé.' },
  { q: 'Une personne répète toujours la même idée. Que fais-tu ?', a: 'Je montre que son idée a été entendue et notée, puis je relance sur le point suivant', d: ['Je lui dis d’arrêter', 'Je l’ignore', 'Je répète aussi mes idées'], e: '« On a bien noté ton idée, on la garde. Passons au point suivant ? » Elle se sent entendue et le groupe avance.' },
  { q: 'Pourquoi faire des points d’étape pendant la discussion ?', a: 'Pour vérifier les accords, gérer le temps et éviter de tourner en rond', d: ['Pour montrer au jury qu’on est le chef', 'Pour remplir les silences', 'Ce n’est pas utile'], e: 'Les points d’étape structurent le travail du groupe : c’est l’un des comportements les plus valorisés.' },
  { q: 'Après l’épreuve, un membre du jury te demande comment tu as vécu l’exercice. Que réponds-tu ?', a: 'Une analyse honnête : ce que j’ai bien fait et ce que j’améliorerais', d: ['Que c’était parfait', 'Que les autres candidats étaient mauvais', 'Que l’exercice ne sert à rien'], e: 'Savoir s’auto-évaluer avec lucidité, sans critiquer les autres, est une qualité recherchée.' },
  { q: 'Un candidat propose une idée dangereuse dans un sujet de survie. Que fais-tu ?', a: 'J’explique calmement le risque et je propose une alternative', d: ['Je laisse faire pour éviter le conflit', 'Je me moque de l’idée', 'Je dis que c’est stupide'], e: 'Argumenter sur la sécurité avec une alternative concrète, c’est faire preuve de jugement.' },
  { q: 'Combien de temps faut-il parler idéalement à chaque intervention ?', a: 'Court : une idée, un argument, en 20 à 40 secondes environ', d: ['Le plus longtemps possible', 'Une seule phrase de 3 mots', 'Au moins 2 minutes pour être complet'], e: 'Des interventions courtes et claires laissent de la place aux autres et sont mieux retenues.' },
  { q: 'Le groupe choisit une solution qui te semble moyenne mais acceptable. Que fais-tu ?', a: 'Je m’y rallie et j’aide à l’améliorer', d: ['Je bloque la décision', 'Je refuse de participer à la suite', 'Je relance le débat depuis le début'], e: 'Mieux vaut une solution commune améliorée qu’un blocage. On peut signaler ses réserves, puis s’engager.' },
  { q: 'Quelle attitude est la plus pénalisante en épreuve de groupe ?', a: 'Monopoliser la parole ou dénigrer les autres', d: ['Changer d’avis', 'Poser des questions', 'Faire une synthèse'], e: 'Monopoliser ou dénigrer est perçu comme un manque d’esprit d’équipe, rédhibitoire pour un futur officier.' },
];

registerBank({ id: 'ent.groupe', module: 'entretien', group: 'Épreuve de groupe', title: 'Épreuve de groupe : les bons réflexes', desc: 'Situations de groupe : que faire ? (30 questions)', items: ITEMS, timeLimit: 30 });
