// English grammar — 48 questions, levels 1 (B1) → 3 (C1).
export const GRAMMAR = [
  // ---- Level 1
  { l: 1, q: 'I ___ in Lyon since 2020.', a: 'have lived', d: ['live', 'lived', 'am living'], e: '<b>Since</b> + a starting point → present perfect: the action started in the past and continues now. (FR : « j’habite à Lyon depuis 2020 » → present perfect en anglais.)' },
  { l: 1, q: 'She ___ to London last summer.', a: 'went', d: ['has gone', 'goes', 'has been going'], e: '<b>Last summer</b> is a finished time → simple past. The present perfect is impossible with a finished time expression.' },
  { l: 1, q: 'Look! The plane ___ off right now.', a: 'is taking', d: ['takes', 'took', 'has taken'], e: '<b>Right now / Look!</b> → present continuous for an action happening at the moment of speaking.' },
  { l: 1, q: 'There isn’t ___ fuel left in the tank.', a: 'much', d: ['many', 'a few', 'several'], e: '<b>Fuel</b> is uncountable → much / a little. <b>Many / a few</b> go with countable nouns (many aircraft, a few pilots).' },
  { l: 1, q: 'He has been a pilot ___ ten years.', a: 'for', d: ['since', 'during', 'ago'], e: '<b>For</b> + a duration (ten years). <b>Since</b> + a starting point (since 2016). <b>Ago</b> goes with the simple past (ten years ago).' },
  { l: 1, q: 'The briefing starts ___ 8 a.m. ___ Monday.', a: 'at / on', d: ['in / on', 'on / at', 'at / in'], e: '<b>At</b> + clock time, <b>on</b> + day/date, <b>in</b> + month/year/season.' },
  { l: 1, q: 'This aircraft is ___ than the old one.', a: 'faster', d: ['more fast', 'fastest', 'more faster'], e: 'Short adjective (one syllable) → <b>-er</b> for the comparative: fast → faster. Never “more faster”.' },
  { l: 1, q: 'Can you give me some ___ about the course?', a: 'information', d: ['informations', 'an information', 'informations pieces'], e: '<b>Information</b> is uncountable in English: no plural, no “an”. Same for advice, news, equipment, luggage.' },
  { l: 1, q: 'Everybody ___ ready for the inspection.', a: 'is', d: ['are', 'be', 'were being'], e: '<b>Everybody / everyone / nobody</b> take a <b>singular</b> verb: everybody is ready.' },
  { l: 1, q: 'You’re a cadet, ___?', a: 'aren’t you', d: ['isn’t it', 'don’t you', 'are you'], e: 'Question tag: positive sentence with <b>be</b> → negative tag with the same auxiliary and subject: you are → <b>aren’t you</b>.' },
  { l: 1, q: 'I ___ go to the gym on Saturdays; it’s a habit.', a: 'usually', d: ['use to', 'am used', 'got used'], e: 'Frequency adverb <b>usually</b> before the main verb. “Use to” (without -d) only appears after did/didn’t.' },
  { l: 1, q: 'Tell ___ about your motivation.', a: 'me', d: ['to me', 'for me', 'at me'], e: '<b>Tell</b> takes a direct personal object: tell me. <b>Say</b> doesn’t: say something to me.' },
  { l: 1, q: 'How ___ pilots are there in your squadron?', a: 'many', d: ['much', 'lot', 'few of'], e: '<b>Pilots</b> is countable plural → how many.' },
  { l: 1, q: 'The film was so ___ that I fell asleep.', a: 'boring', d: ['bored', 'bore', 'boredom'], e: '<b>-ing</b> adjective describes what causes the feeling (a boring film); <b>-ed</b> describes the person who feels it (I was bored).' },
  { l: 1, q: 'We didn’t go out ___ the storm.', a: 'because of', d: ['because', 'although', 'despite of'], e: '<b>Because of</b> + noun (the storm). <b>Because</b> + clause (because it was stormy).' },
  { l: 1, q: 'She ___ speak three languages when she was ten.', a: 'could', d: ['can', 'may', 'must'], e: 'Past ability → <b>could</b>.' },
  // ---- Level 2
  { l: 2, q: 'By the time we arrived at the airfield, the aircraft ___.', a: 'had already left', d: ['already left', 'has already left', 'was already leaving'], e: 'An action completed <b>before another past action</b> → past perfect (had + past participle).' },
  { l: 2, q: 'If it rains tomorrow, they ___ the air show.', a: 'will cancel', d: ['would cancel', 'cancel', 'would have cancelled'], e: 'First conditional (real possibility): <b>If + present, will + verb</b>.' },
  { l: 2, q: 'If I ___ you, I would revise my maths every day.', a: 'were', d: ['am', 'had been', 'would be'], e: 'Second conditional (imaginary situation): <b>If + past, would + verb</b>. With “I”, formal English uses <b>were</b>.' },
  { l: 2, q: 'The runway ___ every morning before the first flight.', a: 'is inspected', d: ['inspects', 'is inspecting', 'has inspect'], e: 'Passive voice, present simple: <b>is/are + past participle</b>. The runway doesn’t inspect anything: it receives the action.' },
  { l: 2, q: 'I’m really looking forward to ___ you at the base.', a: 'seeing', d: ['see', 'have seen', 'be seeing'], e: 'In <b>look forward to</b>, “to” is a preposition → followed by a gerund (-ing).' },
  { l: 2, q: 'He suggested ___ the mission because of the weather.', a: 'postponing', d: ['to postpone', 'postpone', 'that postponing'], e: '<b>Suggest</b> + gerund (suggest doing) or suggest that + subject + base verb. Never “suggest to do”.' },
  { l: 2, q: 'She is used to ___ up at 5 a.m.', a: 'getting', d: ['get', 'got', 'have got'], e: '<b>Be used to + -ing</b> = be accustomed to. Different from <b>used to + base verb</b> (past habit).' },
  { l: 2, q: 'He said that he ___ tired after the night flight.', a: 'was', d: ['is', 'has been being', 'will be'], e: 'Reported speech: the verb usually moves one tense back: “I am tired” → he said he <b>was</b> tired.' },
  { l: 2, q: 'The officer ___ I spoke to was very helpful.', a: 'who', d: ['which', 'whose', 'what'], e: 'Relative pronoun for a person → <b>who</b> (or that, or nothing). <b>Which</b> is for things; <b>whose</b> shows possession.' },
  { l: 2, q: 'You ___ wear a seat belt during take-off. It’s compulsory.', a: 'must', d: ['needn’t', 'may', 'could'], e: '<b>Must</b> expresses obligation. <b>Needn’t</b> = it isn’t necessary.' },
  { l: 2, q: '___ being exhausted, he finished the run.', a: 'Despite', d: ['Although', 'Even', 'However'], e: '<b>Despite / In spite of</b> + noun or -ing. <b>Although</b> + full clause (Although he was exhausted…).' },
  { l: 2, q: 'The more you train, the ___ you get.', a: 'better', d: ['best', 'more good', 'good'], e: 'Structure <b>the + comparative…, the + comparative</b>: the more…, the better.' },
  { l: 2, q: 'I wish I ___ more time to revise.', a: 'had', d: ['have', 'would have', 'will have'], e: '<b>Wish + past simple</b> for a present situation you would like to be different.' },
  { l: 2, q: 'The new hangar ___ next year.', a: 'will be built', d: ['will build', 'is building', 'builds'], e: 'Future passive: <b>will be + past participle</b>.' },
  { l: 2, q: 'I have never ___ such a powerful aircraft.', a: 'flown', d: ['flew', 'flied', 'fly'], e: 'Present perfect = have + <b>past participle</b>. Fly – flew – <b>flown</b>.' },
  { l: 2, q: 'Let’s take a break, ___?', a: 'shall we', d: ['will you', 'don’t we', 'let we'], e: 'The question tag after <b>Let’s</b> is always <b>shall we</b>.' },
  // ---- Level 3
  { l: 3, q: 'If he had trained harder, he ___ the physical test.', a: 'would have passed', d: ['would pass', 'had passed', 'will have passed'], e: 'Third conditional (imaginary past): <b>If + past perfect, would have + past participle</b>.' },
  { l: 3, q: 'Not only ___ the written test, but she also aced the interview.', a: 'did she pass', d: ['she passed', 'she did pass', 'passed she'], e: 'After a negative adverbial at the start (<b>Not only, Never, Rarely</b>…), English uses <b>inversion</b> like a question: did she pass.' },
  { l: 3, q: 'Hardly ___ landed when the storm broke.', a: 'had we', d: ['we had', 'did we', 'we have'], e: '<b>Hardly … when</b> + past perfect with inversion: Hardly had we landed when…' },
  { l: 3, q: 'You ___ have told me the briefing was cancelled! I waited for an hour.', a: 'should', d: ['must', 'can', 'would'], e: '<b>Should have + past participle</b> = criticism/regret about the past (you didn’t tell me, but it would have been right).' },
  { l: 3, q: 'He ___ have seen the warning light; it was switched off.', a: 'can’t', d: ['mustn’t', 'shouldn’t', 'needn’t'], e: 'Deduction about the past: <b>can’t have</b> = it’s impossible that… ; <b>must have</b> = it’s almost certain that…' },
  { l: 3, q: 'It’s high time we ___ for the exam.', a: 'started revising', d: ['start revising', 'will start revising', 'have started to revise'], e: '<b>It’s (high) time + subject + past simple</b>: it expresses that something should already be happening.' },
  { l: 3, q: 'The candidate, ___ father is a navy pilot, was very motivated.', a: 'whose', d: ['who', 'which', 'whom'], e: '<b>Whose</b> expresses possession (his father → whose father).' },
  { l: 3, q: 'Had I known about the test, I ___ prepared better.', a: 'would have', d: ['will have', 'had', 'would'], e: 'Inverted third conditional: <b>Had I known</b> = If I had known → would have + past participle.' },
  { l: 3, q: 'The engine needs ___.', a: 'servicing', d: ['to service', 'service', 'serviced'], e: '<b>Need + -ing</b> has a passive meaning: the engine needs servicing = needs to be serviced.' },
  { l: 3, q: 'She insisted that he ___ the checklist again.', a: 'read', d: ['reads', 'would reading', 'to read'], e: 'Subjunctive after <b>insist / demand / recommend that</b>: base form, without -s (that he read).' },
  { l: 3, q: '___ the weather improves, the flight will be cancelled.', a: 'Unless', d: ['If', 'Provided', 'As long as'], e: '<b>Unless</b> = if … not: the flight will be cancelled if the weather does not improve.' },
  { l: 3, q: 'By next June, I ___ for this selection for over a year.', a: 'will have been preparing', d: ['will prepare', 'am preparing', 'have prepared'], e: 'Future perfect continuous: duration of an activity up to a point in the future.' },
  { l: 3, q: 'Rarely ___ such a calm pilot in an emergency.', a: 'have I met', d: ['I have met', 'I met', 'did I met'], e: 'Negative adverb <b>Rarely</b> at the start → inversion: have I met.' },
  { l: 3, q: 'The report, ___ was published yesterday, criticises the budget.', a: 'which', d: ['that', 'what', 'who'], e: 'In a <b>non-defining</b> relative clause (between commas), use <b>which</b> for things, never <b>that</b>.' },
  { l: 3, q: 'I’d rather you ___ the cockpit without permission.', a: 'didn’t enter', d: ['don’t enter', 'not enter', 'won’t enter'], e: '<b>Would rather + subject + past simple</b> to express a preference about someone else’s present/future action.' },
  { l: 3, q: 'No sooner had the aircraft taken off ___ the engine failed.', a: 'than', d: ['when', 'that', 'then'], e: 'Fixed structure: <b>No sooner … than</b> (but Hardly / Scarcely … when).' },
];
