// Vocabulary: aviation (FR → EN), general / C1 (false friends, phrasal verbs, collocations, idioms), ICAO phraseology.
// [français, english, distracteurs…, note]
const AERO = [
  ['le train d’atterrissage', 'the landing gear', ['the landing train', 'the wheel set', 'the ground rail']],
  ['les volets', 'the flaps', ['the shutters', 'the slats', 'the spoilers'], 'Slats = becs de bord d’attaque ; spoilers = aérofreins/destructeurs de portance.'],
  ['la gouverne de direction', 'the rudder', ['the elevator', 'the aileron', 'the trim']],
  ['la gouverne de profondeur', 'the elevator', ['the rudder', 'the lift', 'the deep control']],
  ['le palonnier', 'the rudder pedals', ['the stick', 'the throttle', 'the brake lever']],
  ['le manche', 'the control stick / control column', ['the handle', 'the throttle', 'the sleeve']],
  ['la manette des gaz', 'the throttle', ['the gas handle', 'the mixture', 'the trigger']],
  ['la piste', 'the runway', ['the track', 'the taxiway', 'the apron']],
  ['la voie de circulation', 'the taxiway', ['the runway', 'the traffic lane', 'the airway']],
  ['l’aire de stationnement', 'the apron', ['the parking lot', 'the hangar', 'the threshold']],
  ['le seuil de piste', 'the runway threshold', ['the runway door', 'the runway limit line', 'the stopway']],
  ['la remise de gaz', 'the go-around', ['the take-off', 'the touch-down', 'the throttle back']],
  ['le décrochage', 'the stall', ['the spin', 'the dive', 'the drop']],
  ['la vrille', 'the spin', ['the stall', 'the roll', 'the loop']],
  ['le cisaillement de vent', 'wind shear', ['wind cut', 'cross wind', 'wind chill']],
  ['le vent de travers', 'crosswind', ['headwind', 'tailwind', 'wind shear']],
  ['le givrage', 'icing', ['freezing rain only', 'frosting', 'snowing']],
  ['le carburant', 'fuel', ['gas oil', 'combustive', 'oil']],
  ['l’hélice', 'the propeller', ['the helix', 'the rotor', 'the fan blade']],
  ['l’horizon artificiel', 'the attitude indicator', ['the horizon meter', 'the altimeter', 'the heading indicator']],
  ['l’anémomètre', 'the airspeed indicator', ['the anemometer gauge', 'the variometer', 'the tachometer']],
  ['le variomètre', 'the vertical speed indicator', ['the variometer gauge', 'the altimeter', 'the turn coordinator']],
  ['le cap', 'the heading', ['the cape', 'the track', 'the course line']],
  ['la route (suivie au sol)', 'the track', ['the road', 'the heading', 'the bearing']],
  ['la dérive (effet du vent)', 'drift', ['derivative', 'slide', 'fin']],
  ['la panne moteur', 'engine failure', ['engine breakdown lane', 'motor fault line', 'engine stop sign']],
  ['un atterrissage forcé', 'a forced landing', ['an obliged landing', 'a hard runway', 'a crash approach']],
  ['le poste de pilotage', 'the cockpit / flight deck', ['the pilot post', 'the cabin', 'the control room']],
  ['le ravitaillement en vol', 'air-to-air refuelling', ['in-flight shopping', 'air feeding', 'fuel dumping']],
  ['un ailier', 'a wingman', ['a winger', 'a co-pilot', 'a flight leader']],
  ['un escadron', 'a squadron', ['a squad', 'a scramble', 'a wing']],
  ['une base aérienne', 'an air base', ['an airport station', 'an aerodrome hall', 'an air camp']],
  ['le siège éjectable', 'the ejection seat', ['the ejecting chair', 'the jump seat', 'the safety seat']],
  ['une rafale (de vent)', 'a gust', ['a burst', 'a blast', 'a breeze']],
  ['le plafond (nuages)', 'the ceiling', ['the roof', 'the top', 'the cover']],
  ['un orage', 'a thunderstorm', ['an orage', 'a shower', 'a lightning']],
  ['le brouillard', 'fog', ['mist only', 'smog', 'haze']],
  ['la tour de contrôle', 'the control tower', ['the command tower', 'the watch room', 'the radar station']],
  ['un aéronef', 'an aircraft', ['an aeronef', 'an airship', 'an aircrafts']],
  ['l’équipage', 'the crew', ['the team cabin', 'the equipment', 'the staff room']],
];

const GENERAL = [
  { l: 1, q: '“Actually” means:', a: 'en fait / en réalité', d: ['actuellement', 'activement', 'exactement'], e: '<b>False friend</b>: actually = in fact. “Actuellement” = currently / at present.' },
  { l: 1, q: '“Eventually” means:', a: 'finalement / à la fin', d: ['éventuellement', 'évidemment', 'en cas d’urgence'], e: '<b>False friend</b>: eventually = in the end. “Éventuellement” = possibly.' },
  { l: 1, q: 'A sensible decision is a decision that is:', a: 'reasonable', d: ['emotional', 'sensitive', 'fragile'], e: '<b>Sensible</b> = raisonnable. “Sensible” in French = sensitive.' },
  { l: 1, q: 'To attend a meeting means to:', a: 'be present at it', d: ['wait for it', 'organise it', 'cancel it'], e: '<b>False friend</b>: attend = assister à. “Attendre” = to wait (for).' },
  { l: 1, q: 'A library is a place where you:', a: 'borrow books', d: ['buy books', 'print money', 'repair engines'], e: '<b>Library</b> = bibliothèque. A bookshop (bookstore) is “une librairie”.' },
  { l: 1, q: '“To realise” means:', a: 'to become aware of something', d: ['to carry out a project', 'to film a movie', 'to sell something'], e: '<b>Realise</b> = se rendre compte. “Réaliser un projet” = to carry out / to achieve a project.' },
  { l: 1, q: 'Choose the correct collocation: to ___ a decision', a: 'make', d: ['do', 'take part', 'have done'], e: 'We <b>make</b> a decision (also “take” in British English), but we never “do” a decision.' },
  { l: 1, q: 'Choose the correct collocation: to ___ attention', a: 'pay', d: ['make', 'give back', 'do'], e: 'Fixed expression: <b>pay attention</b> (to something).' },
  { l: 1, q: '“A piece of cake” means:', a: 'something very easy', d: ['a small reward', 'a birthday party', 'a difficult task'], e: 'Idiom: <b>a piece of cake</b> = very easy.' },
  { l: 1, q: '“To give up” means:', a: 'to stop trying / to quit', d: ['to give a present', 'to raise your hand', 'to increase'], e: 'Phrasal verb <b>give up</b> = abandonner.' },
  { l: 1, q: 'A “salary” is:', a: 'the money you earn for your job', d: ['a type of salad', 'a dirty room', 'a military rank'], e: '<b>Salary</b> = salaire (paid monthly). <b>Wages</b> are usually paid weekly or hourly.' },
  { l: 1, q: '“To run out of fuel” means:', a: 'to have no fuel left', d: ['to spill fuel', 'to buy fuel quickly', 'to refuel'], e: 'Phrasal verb <b>run out of</b> = ne plus avoir de, être à court de.' },
  { l: 2, q: '“To put off” a meeting means to:', a: 'postpone it', d: ['cancel it forever', 'start it', 'organise it'], e: '<b>Put off</b> = reporter (postpone). <b>Call off</b> = annuler.' },
  { l: 2, q: '“To call off” the mission means to:', a: 'cancel it', d: ['phone the crew', 'start it', 'delay it slightly'], e: '<b>Call off</b> = annuler.' },
  { l: 2, q: '“To carry out” an inspection means to:', a: 'perform it', d: ['avoid it', 'carry it outside', 'prepare it'], e: '<b>Carry out</b> = effectuer, réaliser.' },
  { l: 2, q: '“To come up with” an idea means to:', a: 'think of it / suggest it', d: ['reject it', 'copy it', 'forget it'], e: '<b>Come up with</b> = trouver, proposer (une idée, une solution).' },
  { l: 2, q: '“To turn down” an offer means to:', a: 'refuse it', d: ['accept it', 'lower the volume', 'discuss it'], e: '<b>Turn down</b> = refuser (an offer, a request). Also “baisser” (the volume).' },
  { l: 2, q: '“To break the ice” means to:', a: 'make people feel more relaxed at the start', d: ['to destroy something', 'to start a fight', 'to cool a drink'], e: 'Idiom: <b>break the ice</b> = briser la glace.' },
  { l: 2, q: '“Once in a blue moon” means:', a: 'very rarely', d: ['every month', 'at night', 'when it’s cold'], e: 'Idiom: <b>once in a blue moon</b> = très rarement.' },
  { l: 2, q: '“Reliable” describes someone who:', a: 'you can count on', d: ['tells lies', 'is very rich', 'is always late'], e: '<b>Reliable</b> = fiable. Noun: reliability.' },
  { l: 2, q: '“Demanding” training is:', a: 'difficult and requires a lot of effort', d: ['asked for by everyone', 'cheap', 'optional'], e: '<b>Demanding</b> = exigeant. False friend: “demander” = to ask.' },
  { l: 2, q: 'Choose the right word: the pilot showed great ___ under pressure.', a: 'composure', d: ['composition', 'compost', 'complacency'], e: '<b>Composure</b> = sang-froid, calme. <b>Complacency</b> = autosatisfaction (a danger in aviation!).' },
  { l: 2, q: '“To be in charge of” means:', a: 'to be responsible for', d: ['to be paid for', 'to be accused of', 'to be charged with a crime'], e: '<b>In charge of</b> = responsable de. (To be charged with = être accusé de.)' },
  { l: 2, q: 'A “skill” is:', a: 'an ability you develop', d: ['a type of plane', 'a mistake', 'a skull'], e: '<b>Skill</b> = compétence. Soft skills = savoir-être (teamwork, communication…).' },
  { l: 3, q: '“To hit the nail on the head” means:', a: 'to describe exactly what is causing a situation', d: ['to have an accident', 'to work with tools', 'to be very angry'], e: 'Idiom: <b>hit the nail on the head</b> = mettre le doigt dessus, viser juste.' },
  { l: 3, q: '“To be on the same page” means:', a: 'to agree / share the same understanding', d: ['to read the same book', 'to be in the same class', 'to be confused'], e: 'Idiom used in teamwork: <b>be on the same page</b> = être sur la même longueur d’onde.' },
  { l: 3, q: '“A setback” is:', a: 'a problem that delays progress', d: ['a seat at the back', 'a reward', 'a retirement'], e: '<b>Setback</b> = revers, contretemps.' },
  { l: 3, q: '“Thorough” preparation is:', a: 'complete and careful', d: ['quick and rough', 'through a tunnel', 'dangerous'], e: '<b>Thorough</b> = minutieux, approfondi. (Not “through” = à travers.)' },
  { l: 3, q: '“To cope with” stress means to:', a: 'deal with it successfully', d: ['create it', 'avoid it completely', 'copy it'], e: '<b>Cope with</b> = faire face à, gérer.' },
  { l: 3, q: '“Commitment” is closest in meaning to:', a: 'dedication', d: ['committee', 'commission', 'compliment'], e: '<b>Commitment</b> = engagement, dévouement — a key word for a military interview in English.' },
  { l: 3, q: 'Which word means “a short period of intense effort”?', a: 'a burst', d: ['a bust', 'a boost', 'a beast'], e: '<b>A burst</b> (of energy, of speed) = une rafale, un sursaut.' },
  { l: 3, q: '“Hindsight” means:', a: 'understanding a situation after it has happened', d: ['the ability to see behind you', 'prediction', 'a blind spot'], e: '<b>With hindsight</b> = avec le recul. Useful for debriefs!' },
  { l: 3, q: '“To overcome” a difficulty means to:', a: 'succeed in dealing with it', d: ['to come too early', 'to ignore it', 'to cause it'], e: '<b>Overcome</b> = surmonter.' },
  { l: 3, q: '“Straightforward” means:', a: 'simple / easy to understand', d: ['straight ahead only', 'stubborn', 'very fast'], e: '<b>Straightforward</b> = simple, direct.' },
  { l: 3, q: '“Accountable” means:', a: 'responsible and required to explain your actions', d: ['good at accounting', 'countable', 'acceptable'], e: '<b>Accountable</b> = responsable (qui doit rendre des comptes).' },
  { l: 3, q: '“Pending” approval means approval is:', a: 'not yet given, still waiting', d: ['refused', 'hanging on a wall', 'final'], e: '<b>Pending</b> = en attente.' },
];

const PHRASEO = [
  { q: 'In radiotelephony, “ROGER” means:', a: 'I have received all of your last transmission', d: ['I will comply', 'Yes', 'Repeat your message'], e: '<b>Roger</b> = message reçu. It does NOT mean “yes” or “I will comply”.' },
  { q: '“WILCO” means:', a: 'I understand your message and will comply with it', d: ['I have received your message', 'Wait', 'Cancel'], e: '<b>Wilco</b> = will comply.' },
  { q: '“AFFIRM” means:', a: 'Yes', d: ['I confirm my position', 'Repeat', 'Approved'], e: 'ICAO uses <b>affirm</b> for “yes” (not “affirmative”, which can be confused with “negative”).' },
  { q: '“NEGATIVE” means:', a: 'No / permission not granted / that is not correct', d: ['Yes', 'I cannot hear you', 'Emergency'], e: '<b>Negative</b> = non.' },
  { q: '“SAY AGAIN” means:', a: 'Repeat all or part of your last transmission', d: ['I repeat my message', 'Speak louder', 'Change frequency'], e: '<b>Say again</b> = répétez. Never “repeat”, which is used in a military context for artillery fire.' },
  { q: '“STANDBY” means:', a: 'Wait and I will call you', d: ['Stop the engine', 'Go ahead', 'Land immediately'], e: '<b>Standby</b> = attendez, je vous rappelle.' },
  { q: '“READ BACK” means:', a: 'Repeat all, or the specified part, of this message back to me exactly as received', d: ['Read the checklist', 'Go back to the previous frequency', 'Read the NOTAM'], e: 'The pilot must <b>read back</b> clearances (runway, altitude, heading, frequency, squawk…).' },
  { q: '“UNABLE” means:', a: 'I cannot comply with your request', d: ['I cannot hear you', 'I am in distress', 'I am not ready yet'], e: '<b>Unable</b> = impossible de se conformer.' },
  { q: '“DISREGARD” means:', a: 'Ignore (my last message)', d: ['Repeat', 'Confirm', 'Hurry up'], e: '<b>Disregard</b> = ignorez.' },
  { q: '“CORRECTION” means:', a: 'An error has been made; the correct version is…', d: ['Your readback was correct', 'Change heading', 'Cancel the flight'], e: '<b>Correction</b> = rectification.' },
  { q: '“HOW DO YOU READ?” means:', a: 'What is the readability of my transmission?', d: ['What is your altitude?', 'Can you read the chart?', 'Did you read the NOTAM?'], e: 'Answer on a scale of 1 to 5: “Read you five” = perfectly readable.' },
  { q: '“MAYDAY, MAYDAY, MAYDAY” indicates:', a: 'a distress situation (grave and imminent danger)', d: ['an urgency situation without immediate danger', 'a radio check', 'a change of runway'], e: '<b>Mayday</b> = détresse. <b>Pan-pan</b> = urgence (sans danger grave et imminent).' },
  { q: '“PAN-PAN, PAN-PAN, PAN-PAN” indicates:', a: 'an urgency situation', d: ['a distress situation', 'a routine message', 'a fuel request'], e: '<b>Pan-pan</b> = urgence : sécurité de l’aéronef ou d’une personne en cause, sans danger imminent.' },
  { q: 'Transponder code 7700 means:', a: 'emergency', d: ['radio failure', 'unlawful interference (hijack)', 'VFR flight'], e: '<b>7700</b> = emergency ; <b>7600</b> = radio failure ; <b>7500</b> = unlawful interference. (« 75 on vit, 76 on parle plus, 77 on meurt »).' },
  { q: 'Transponder code 7600 means:', a: 'radio communication failure', d: ['emergency', 'hijack', 'military flight'], e: '<b>7600</b> = panne radio.' },
  { q: '“LINE UP AND WAIT” means:', a: 'Enter the runway and wait for take-off clearance', d: ['You are cleared for take-off', 'Wait at the holding point', 'Queue behind other aircraft on the taxiway'], e: 'Line up and wait = alignez-vous et attendez. It is NOT a take-off clearance.' },
  { q: '“HOLD SHORT OF RUNWAY 27” means:', a: 'Stop before entering runway 27', d: ['Land short on runway 27', 'Cross runway 27', 'Take off from runway 27'], e: '<b>Hold short</b> = maintenez avant (la piste).' },
  { q: '“GO AROUND” means:', a: 'Abort the approach and climb', d: ['Taxi around the airport', 'Fly a holding pattern', 'Land on the other runway'], e: '<b>Go around</b> = remettez les gaz.' },
  { q: '“CLEARED” means:', a: 'Authorised to proceed under the conditions specified', d: ['The runway is clean', 'The weather is clear', 'You are free to do what you want'], e: '<b>Cleared</b> = autorisé.' },
  { q: 'Runway “27” is oriented approximately:', a: 'towards 270° (West)', d: ['towards 027° (North-North-East)', 'towards 090° (East)', 'towards 207°'], e: 'A runway number = its magnetic heading divided by 10: 27 → <b>270°</b>.' },
  { q: '“Wind 240 degrees, 15 knots” means the wind:', a: 'comes FROM 240° at 15 kt', d: ['blows TOWARDS 240°', 'is variable', 'has gusts of 240 kt'], e: 'Wind direction is always where the wind <b>comes from</b>.' },
  { q: '“Climb flight level 80” means climb to:', a: 'FL 080, i.e. 8,000 ft on the standard setting 1013 hPa', d: ['8,000 m', '800 ft', '80,000 ft'], e: 'Flight level = altitude in hundreds of feet with the altimeter set to <b>1013 hPa</b>.' },
  { q: 'QNH is the pressure setting that makes the altimeter show:', a: 'the altitude above mean sea level', d: ['the height above the runway', 'the flight level', 'the true airspeed'], e: '<b>QNH</b> → altitude above sea level. <b>QFE</b> → height above the airfield. <b>1013</b> → flight levels.' },
  { q: 'How is the digit 9 pronounced in ICAO radiotelephony?', a: 'NIN-ER', d: ['NINE', 'NAIN', 'NEUF'], e: '9 = <b>niner</b> (to avoid confusion with the German “nein”). Also 3 = “tree”, 5 = “fife”.' },
  { q: 'How is the digit 3 pronounced?', a: 'TREE', d: ['THREE', 'TRI', 'TERCE'], e: '3 = <b>tree</b>.' },
  { q: '“EXPEDITE” means:', a: 'Do it as quickly as possible', d: ['Send a message', 'Slow down', 'Cancel'], e: '<b>Expedite</b> (descent, climb, vacate the runway) = accélérez, faites vite.' },
  { q: '“REPORT FINAL” means:', a: 'Tell me when you are on final approach', d: ['Send your final report', 'This is the last message', 'Land now'], e: 'Report = signalez (une position).' },
  { q: '“VACATE THE RUNWAY” means:', a: 'Leave the runway', d: ['Clean the runway', 'Hold on the runway', 'Line up'], e: '<b>Vacate</b> = dégagez.' },
  { q: '“CONTACT TOWER 118.7” means:', a: 'Change frequency to 118.7 and call the tower', d: ['The tower will call you on 118.7', 'Listen only on 118.7', 'Squawk 1187'], e: '<b>Contact</b> = establish communication. <b>Monitor</b> = listen (without calling).' },
  { q: '“MONITOR GROUND 121.9” means:', a: 'Listen out on 121.9 without calling', d: ['Call ground on 121.9', 'Watch the ground', 'Taxi to the ground'], e: '<b>Monitor</b> = écoutez la fréquence.' },
  { q: 'What is said to end a conversation when no answer is expected?', a: 'OUT', d: ['OVER', 'ROGER', 'BREAK'], e: '<b>Over</b> = I expect a reply ; <b>Out</b> = end of exchange (rarely used in VHF). Never “over and out”.' },
  { q: 'The phonetic spelling of “F-HBCJ” is:', a: 'Foxtrot Hotel Bravo Charlie Juliett', d: ['Fox Hotel Bravo Charlie Juliet', 'Foxtrot Hotel Beta Charlie Julia', 'Foxtrot Hotel Bravo Coca Juliett'], e: 'ICAO alphabet: F = <b>Foxtrot</b>, H = <b>Hotel</b>, B = <b>Bravo</b>, C = <b>Charlie</b>, J = <b>Juliett</b>.' },
];

export { AERO, GENERAL, PHRASEO };

// Questions de vocabulaire aéronautique générées dans les deux sens.
export const AERO_ITEMS = AERO.flatMap(([fr, en, d, note], i) => [
  { l: 1, q: `How do you say <b>« ${fr} »</b> in English?`, a: en, d, e: `<b>${fr}</b> = <b>${en}</b>.${note ? ' ' + note : ''}` },
  { l: 2, q: `What does <b>“${en}”</b> mean?`, a: fr, d: AERO.filter((_, j) => j !== i).sort((x, y) => ((i * 7 + x[0].length) % 5) - ((i * 7 + y[0].length) % 5)).slice(0, 3).map((x) => x[0]), e: `<b>${en}</b> = <b>${fr}</b>.${note ? ' ' + note : ''}` },
]);
